### PR TITLE
Dynamic pricing - Data Science Application presentation

### PR DESCRIPTION
**Pull request by ngaya3**
[Data Science Application.pptx](https://github.com/pyousefi/MOTIS_PROJECTS/files/1777592/Data.Science.Application.pptx)

### CODE REVIEW

**Comment by ngaya3** [comment]
titanic submission
 

My Titanic survival prediction screenshot

**Comment by ngaya3** [comment]
titanic submission


My titanic survival prediction submission screenshot

**Review by pyousefi — CHANGES_REQUESTED** [review]
Please add the files to the directory and commit the directory.

**Review by ngaya3 — COMMENTED** [review]
Done

**Review by pyousefi — APPROVED** [review]

**Pull request merged**
